version: '3.3'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: job
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/:ro
      - mysql:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      MYSQL_DATABASE: job
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql:
    external: true