filter_params:
  area: '6001001000' # Taipei
  isnew: '14' # (更新日期) 0:本日最新 3:三日內 7:一週內 14:兩週內 30:一個月內
  jobexp: '3'  # (經歷要求) 1年以下,1-3年,3-5年,5-10年,10年以上
  excludeJobKeyword: '前端+後端+系統+Quality+品質+電源+客服+臨床+主管+機構+Golang+Unity+HW+Server+派遣+Hardware+Stack+FW+ASIC+iOS+QA+Android+Electrical+5G+Design+副理+實習生+Wind+EDI'  # 排除關鍵字
  kwop: '1'  # 只搜尋職務名稱
  