filter_params:
  area: '6001001000' # Taipei
  isnew: '7' # (更新日期) 0:本日最新 3:三日內 7:一週內 14:兩週內 30:一個月內
  jobexp: '3'  # (經歷要求) 1年以下,1-3年,3-5年,5-10年,10年以上
  excludeJobKeyword: '前端+後端+系統+Quality+品質+電源+客服+臨床+主管+機構+Golang+Unity+HW+Server+派遣+Hardware+Stack+FW+ASIC+iOS+QA+Android+Electrical+5G+Design+副理+實習生+Wind+EDI'  # 排除關鍵字
  kwop: '1'  # 只搜尋職務名稱

job_keywords:
  - '前端'
  - '後端'
  - '系統'
  - '品質'
  - '電源'
  - '客服'
  - '臨床'
  - '主管'
  - '機構'
  - '派遣'
  - '副理'
  - '實習生'
  - '約聘'
  - '資深'
  - '運維'
  - '韌體'
  - '測試'
  - '機械'
  - '製程'
  - '總監'
  - '綠建築'
  - 'Quality'
  - 'Golang'
  - 'Unity'
  - 'HW'
  - 'Server'
  - 'Hardware'
  - 'Stack'
  - 'FW'
  - 'ASIC'
  - 'iOS'
  - 'QA'
  - 'Android'
  - 'Electrical'
  - '5G'
  - 'Design'
  - 'Wind'
  - 'EDI'
  - 'Application '
  - 'MEMS'
  - 'SW'
  - 'Java'
  - 'Senior'
  - 'IC'
  - 'Hardware'
  - 'Test'
  - 'Manager'
  - 'PCB'
  - 'Wireless'
  - 'Internship'
  - 'Game'
  - 'Testing'
  - 'Administrator'
  - 'Compliance'
  - 'Vibration'
  - 'Front-end'
  - 'Firmware'
  - 'Layout'
  - 'Speech'
  - 'Plumbing'
  - 'Structural'
  - 'MSG'
  - 'ID'
  - 'Representative'

  

